### ISSUE TITLE
svg logo

### ISSUE THREAD

**Issue by insxa** [SeedWebs/seed4#1]
Hello, how can i add svg logo ?
I have used this code in theme functions.php
`// Allow SVG
add_filter( 'wp_check_filetype_and_ext', function($data, $file, $filename, $mimes) {

  global $wp_version;
  if ( $wp_version !== '4.7.1' ) {
     return $data;
  }

  $filetype = wp_check_filetype( $filename, $mimes );

  return [
      'ext'             => $filetype['ext'],
      'type'            => $filetype['type'],
      'proper_filename' => $data['proper_filename']
  ];

}, 10, 4 );

function cc_mime_types( $mimes ){
  $mimes['svg'] = 'image/svg+xml';
  return $mimes;
}
add_filter( 'upload_mimes', 'cc_mime_types' );

function fix_svg() {
  echo '<style type="text/css">
        .attachment-266x266, .thumbnail img {
             width: 100% !important;
             height: auto !important;
        }
        </style>';
}
add_action( 'admin_head', 'fix_svg' );`

**Comment by mennwebs** [comment]
From Theme Requirement https://make.wordpress.org/themes/handbook/review/required/

I can't add more functions in functions.php.

You can create Child Theme and add this snippet. Or you can use plugin such as 

- https://wordpress.org/plugins/svg-support/
- https://wordpress.org/plugins/svg-block/
